- name: "Logging into docker"
  shell: "docker login {{ docker_registry_url }} -u {{ docker_registry_username }} --password-stdin"
  args:
    stdin: "{{ docker_registry_password }}"
  register: login
- debug: msg={{ login.stdout }}

- name: "Pushing {{ docker_image }}"
  shell: "docker push {{ docker_image }}"
  register: push
- debug: msg={{ push.stdout }}
